pipeline:
  name: namespace-operation
  identifier: namespaceoperation
  projectIdentifier: demonstration
  orgIdentifier: tif
  tags: {}
  stages:
    - stage:
        name: dryrun
        identifier: dryrun
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: namespace
          environment:
            environmentRef: org.prod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: martinaks2prod
          execution:
            steps:
              - step:
                  type: K8sDryRun
                  name: k8sdryrun
                  identifier: k8sdryrun
                  spec: {}
                  timeout: 1m
              - step:
                  type: ShellScriptProvision
                  name: ShellScriptProvision_1
                  identifier: ShellScriptProvision_1
                  spec:
                    source:
                      type: Inline
                      spec:
                        script: |-
                          cat << EOM > manifest.yaml
                          <+pipeline.stages.dryrun.spec.execution.steps.k8sdryrun.k8s.ManifestDryRun>
                          EOM
                          cat manifest.yaml

                          echo <+pipeline.stages.dryrun.spec.execution.steps.k8sdryrun.k8s.ManifestDryRun>
                    environmentVariables: []
                  timeout: 1m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Abort
