pipeline:
  name: namespace-operation
  identifier: namespaceoperation
  projectIdentifier: demonstration
  orgIdentifier: tif
  tags: {}
  stages:
    - stage:
        name: create_or_update_namespace
        identifier: dryrun
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: namespace
          environment:
            environmentRef: org.prod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: martinaks2prod
          execution:
            steps:
              - step:
                  type: K8sDryRun
                  name: k8sdryrun
                  identifier: k8sdryrun
                  spec: {}
                  timeout: 1m
              - step:
                  type: ShellScriptProvision
                  name: ShellScriptProvision_1
                  identifier: ShellScriptProvision_1
                  spec:
                    source:
                      type: Inline
                      spec:
                        script: |-
                          cat << EOM > manifest.yaml
                          <+pipeline.stages.create_or_update_namespace.spec.execution.steps.k8sdryrun.k8s.ManifestDryRun>
                          EOM
                          cat manifest.yaml

                          echo <+pipeline.stages.drycreate_or_update_namespace.spec.execution.steps.k8sdryrun.k8s.ManifestDryRun>
                    environmentVariables: []
                  timeout: 1m
              - stepGroup:
                  name: create-namespace
                  identifier: createnamespace
                  steps:
                    - step:
                        type: K8sApply
                        name: create-namespace
                        identifier: createnamespace
                        spec:
                          filePaths:
                            - namespaces/artifacts/namespace-create.yaml
                          skipDryRun: false
                          skipSteadyStateCheck: false
                          skipRendering: false
                          overrides: []
                        timeout: 1m
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.operation> == "create"
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Abort
  variables:
    - name: namespace
      type: String
      description: ""
      required: true
      value: <+input>
    - name: bu
      type: String
      description: ""
      required: true
      value: <+input>
    - name: operation
      type: String
      description: ""
      required: true
      value: <+input>.allowedValues(create,update,delete,enableistioinjection,disableistioinjection)
