---
pipeline:
  projectIdentifier: "tifservices"
  orgIdentifier: "tif"
  tags: {}
  stages:
  - stage:
      name: "k8sdeployment"
      identifier: "k8sdeployment"
      description: ""
      type: "Deployment"
      spec:
        deploymentType: "Kubernetes"
        service:
          serviceRef: "<+input>"
          serviceInputs: "<+input>"
        environment:
          environmentRef: "<+input>"
          deployToAll: false
          environmentInputs: "<+input>"
          serviceOverrideInputs: "<+input>"
          infrastructureDefinitions: "<+input>"
        execution:
          steps:
          - step:
              name: "k8srolloutdeployment"
              identifier: "k8srolloutdeployment"
              type: "K8sRollingDeploy"
              timeout: "1m"
              spec:
                skipDryRun: false
                pruningEnabled: false
          rollbackSteps:
          - step:
              name: "Rollback Rollout Deployment"
              identifier: "rollbackRolloutDeployment"
              type: "K8sRollingRollback"
              timeout: "10m"
              spec:
                pruningEnabled: false
      tags: {}
      failureStrategies:
      - onFailure:
          errors:
          - "AllErrors"
          action:
            type: "StageRollback"
  identifier: "k8sdeploymenttoanyenvironment"
  name: "k8sdeployment-to-any-environment"
