pipeline:
  projectIdentifier: tifservices
  orgIdentifier: tif
  tags: {}
  stages:
    - stage:
        name: k8sdeployment
        identifier: k8sdeployment
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: <+input>
            serviceInputs: <+input>
          execution:
            steps:
              - step:
                  type: Queue
                  name: queue-pipeline-on-int-branch
                  identifier: queuepipelineonintbranch
                  spec:
                    key: <+env.identifier>-<+infra.infraIdentifier>
                    scope: Pipeline
                  timeout: 10m
                  when:
                    stageStatus: Success
                    condition: <+infra.infraIdentifier> == 'intbranch'
              - step:
                  type: Wait
                  name: 2m wait
                  identifier: m_wait
                  spec:
                    duration: 2m
              - step:
                  type: K8sRollingDeploy
                  name: k8srolloutdeployment
                  identifier: k8srolloutdeployment
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 2m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
          environment:
            environmentRef: aksdev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: <+pipeline.variables.namespace>
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  identifier: k8sdeploymenttoaksdevbranchnamespaces
  name: k8sdeployment-to-aksdev-branch-namespaces
  variables:
    - name: namespace
      type: String
      description: Enter the namespace to deploy the service
      required: true
      value: <+input>.allowedValues(intbranch,devbranch,atbranch)
