pipeline:
  name: k8sdeployment-to-prod-and-dr-namespaces
  identifier: k8sdeploymenttoprodanddrnamespaces
  projectIdentifier: tifservices
  orgIdentifier: tif
  tags: {}
  stages:
    - stage:
        name: k8sdeployment
        identifier: k8sdeployment
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          environments:
            metadata:
              parallel: true
            values:
              - environmentRef: aksprod
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: prodnamespace
              - environmentRef: aksdr
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: drnamespace
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+pipeline.stages.k8sdeployment.variables.environment>
                          echo <+stage.variables.environment>
                          echo <+env.identifier>
                          echo <+pipeline.variables.envname>
                          echo <+stage.identifier>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 30s
              - step:
                  type: K8sDryRun
                  name: k8sdryrun
                  identifier: k8sdryrun
                  spec: {}
                  timeout: 1m
              - step:
                  type: ShellScript
                  name: copy k8sdryrun file
                  identifier: ShellScript_2
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          PREVIEWDIR="/tmp/k8syamlpreview-<+pipeline.executionId>/"
                          mkdir -p $PREVIEWDIR
                          PREVIEWFILE="$PREVIEWDIR/<+stage.identifier>"

                          cat << EOM > $PREVIEWFILE
                          # pipeline triggered by: <+pipeline.triggeredBy.name>
                          # pipeline triggered by email: <+pipeline.triggeredBy.email> (This returns NULL if the pipeline is triggered using a webhook)
                          # pipeline execution ID: <+pipeline.executionId>
                          # pipeline Name: <+pipeline.name>
                          # pipeline Stage ID: <+stage.identifier>
                          <+pipeline.stages.<+stage.identifier>.spec.execution.steps.k8sdryrun.k8s.manifestDryRun>
                          EOM
                          cat $PREVIEWFILE
                    environmentVariables: []
                    outputVariables: []
                  timeout: 1m
              - step:
                  name: k8srolloutdeployment
                  identifier: k8srolloutdeployment
                  type: K8sRollingDeploy
                  timeout: 3m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
          services:
            values: <+input>
            metadata:
              parallel: true
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        variables:
          - name: environment
            type: String
            description: Environment name variable created from the env the pipeline runs against
            required: false
            value: <+env.identifier>
    - stage:
        name: Post K8s DryRun to Git
        identifier: Post_K8s_DryRun_to_Git
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: post k8s dryrun to git
                  identifier: post_k8s_dryrun_to_git
                  template:
                    templateRef: Post_Anything_to_Git
                    versionLabel: version2
        tags: {}
    - stage:
        name: Test Stage
        identifier: Test_Stage
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          environment:
            environmentRef: aksprod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: prodnamespace
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+env.name>

                          echo <+env.identifier>
                          echo <+pipeline.variables.envname>
                          echo <+pipeline.stages.k8sdeployment.variables.environment>
                          echo <+pipeline.stages.k8sdeployment_0.spec.infrastructure.envRef>
                          echo <+pipeline.stages.k8sdeployment_0.spec.infrastructure.output.environment.environmentRef>
                          echo <+service.identifier>.<+infra.namespace>.svc.cluster.local
                          host <+service.identifier>.<+infra.namespace>.svc.cluster.local

                          echo <+serviceVariables.healthcheckport>
                          echo <+serviceVariables.healthcheckuri>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 30s
              - step:
                  name: Test k8s service DNS name
                  identifier: Test_k8s_service_DNS_name
                  template:
                    templateRef: TestDNSName
                    versionLabel: v1
                    templateInputs:
                      type: ShellScript
                      spec:
                        environmentVariables:
                          - name: dnsname
                            type: String
                            value: <+service.identifier>.<+infra.namespace>.svc.cluster.local
              - step:
                  type: Http
                  name: Test k8 service HTTP
                  identifier: Test_k8_service_HTTP
                  spec:
                    url: http://<+service.identifier>.<+infra.namespace>.svc.cluster.local:<+serviceVariables.healthcheckport>/<+serviceVariables.healthcheckuri>
                    method: GET
                    headers: []
                    inputVariables: []
                    outputVariables: []
                    assertion: <+httpResponseCode> == 200
                  timeout: 30s
              - step:
                  type: Http
                  name: Test Istio Ingress mTLS HTTPS
                  identifier: Test_Istio_Ingress_mTLS_HTTPS
                  spec:
                    url: https://<+serviceVariables.mtlsfqdn>/<+serviceVariables.mtlsuri>
                    method: GET
                    headers: []
                    inputVariables: []
                    outputVariables: []
                    assertion: <+httpResponseCode> == 200
                    certificate: <+secrets.getValue("mtlsclientcert")>
                    certificateKey: <+secrets.getValue("mtlsclientkey")>
                  timeout: 10s
            rollbackSteps: []
          services:
            useFromStage:
              stage: k8sdeployment
            metadata:
              parallel: true
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        when:
          pipelineStatus: Success
  variables:
    - name: envname
      type: String
      description: Environment name variable created from the env the pipeline runs against
      required: false
      value: <+env.identifier>
  allowStageExecutions: false
